# Generated by Django 3.2.9 on 2024-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
